template = "https://github.com/giellalt/template-lang-und"
rev_id = 255
template_sha = "b36832e6713c79f483aee143e866d6cad5dec90e"

[replacements]
__GLOTTOLOG_ID__ = "tata1255"
__REPO__ = "lang-tat"
__UND2C__ = "tt"
__UNDEFINED__ = "Tatar"
__UND__ = "tat"
