template = "https://github.com/giellalt/template-lang-und"
rev_id = 256
template_sha = "4e2ddf168a2aaf68d2c29db9e79e44e1dc4c2b76"

[replacements]
__GLOTTOLOG_ID__ = "tata1255"
__REPO__ = "lang-tat"
__UND2C__ = "tt"
__UNDEFINED__ = "Tatar"
__UND__ = "tat"
